### ISSUE TITLE
A way to communicate with developer.

### ISSUE THREAD

**Issue by atmughrabi** [mbrobbel/capi-streaming-framework#2]
Hello Matthijs,

I am really interested in your CAPI implementation, very structured and clean. What if I want to split the CU copy state to two states or more. for example fetch -> manipulate data -> commit. what Signals should I worry about as I am trying to do that and the wed->status is not being updated. I could be more details but I am trying to find a way to communicate with you, email, skype.

Any hints would be very appreciated. This is the best CAPI implementation I came across. I advise providing Documentation for it, as it could become the basis for more research projects in future.

Thanks a lot in advance.

please respond so I can provide you with my contact info.

**Comment by mbrobbel** [comment]
Hi @atmughrabi,

I'm glad to hear you are interested in the framework. Please feel free to provide me with your contact details. I'd be happy to help you out.

**Comment by atmughrabi** [comment]
Awesome, and thanks a lot, this is my email atmughra@ncsu.edu.
This is my Linkedin: https://www.linkedin.com/in/abdullah-mughrabi-53549b95
